export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const UPDATE_QTY = 'UPDATE_QTY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_COMPARE = 'REMOVE_FROM_COMPARE';